// <auto-generated />
namespace FashionShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _21123quantity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_21123quantity));
        
        string IMigrationMetadata.Id
        {
            get { return "202312210517304_21123quantity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
